version: '3.5' 

services: 
    front:
      build: ./example-frontend
      ports: 
        - 5000:5000
      container_name: example-frontend

    back:
      build: ./example-backend
      ports: 
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_USER=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: example-backend
    
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      container_name: postgres

    redis:
      image: redis