version: '3.5' 

services: 
    web:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - front
        - back
      container_name: web

    front:
      build: ./example-frontend
      ports: 
        - 5000:5000
      container_name: example-frontend

    back:
      build: ./example-backend
      ports: 
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_USER=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: example-backend
    
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      container_name: postgres

    redis:
      image: redis
      container_name: redis